### ISSUE TITLE
Fix nit in section 3.1.4 example of sieve-fcc-00

### ISSUE THREAD

**Issue by brong** [ietfextra/tracking#1]
From: Stan Kalisch <stan@glyphein.mailforce.net>

I ran across one nit in the draft after posting my comments to the list.

Section 3.1.4, line 184:

CURRENT:
      :from "hemingway@example.com" "Gone Fishin';
SUGGESTED:
      :from "hemingway@example.com" "Gone Fishin'";

**Comment by ksmurchison** [comment]
https://github.com/ietfextra/tracking/commit/08e718ff3349254419aff5708aa1c6a1dddc5b86
