### ISSUE TITLE
STATUS=SIZE - document interaction with 64bit draft

### ISSUE THREAD

**Issue by brong** [ietfextra/tracking#10]
There's a comment in draft-bosch-imap-status-size-00:

   [FIXME: Interaction with 64BIT capability]

This needs to be resolved before submission to standards track

**Comment by stephanbosch** [comment]
Right. However, the problem is that the 64BIT capability is not yet published. How should this be handled?

**Comment by brong** [comment]
I would recommend that you define the type as being the same as RFC822.SIZE, and then you don't need to mention anything about 64BIT, because support will naturally fall out of 64BIT when it gets published.

**Comment by stephanbosch** [comment]
I guess that is already the case then, since the SIZE item is described as follows "The total size of the mailbox in octets.  This MUST be equal to the sum of the values of the RFC822.SIZE FETCH message data item [IMAP4rev1] of all messages in the mailbox."

**Comment by brong** [comment]
It seems that it would be fine to just remove any mention of 64BIT considerations then.

**Comment by stephanbosch** [comment]
Ok, removed.
