### ISSUE TITLE
SAVEDATE work out behaviour when unsupported by the implementation

### ISSUE THREAD

**Issue by brong** [ietfextra/tracking#13]
Currently the text says [FIXME: This is what Dovecot currently does, but for a
   standard this is inappropriate.  It should probably indicate the lack
   of support with a particular NO response code, or it could just
   return NULL or some other special value].

This needs to be resolved before publication.

It is also necessary to document how the SEARCH extensions work

**Comment by stephanbosch** [comment]
See the discussions on the mailing list. I am still not sure how to address this.

**Comment by stephanbosch** [comment]
Addressed in latest draft.
