### ISSUE TITLE
list-myrights: add advice to clients about expense

### ISSUE THREAD

**Issue by brong** [ietfextra/tracking#17]
From IETF101 meeting.  It may be expensive for the server to calculate "myrights" for large numbers of folders.

Suggestion: advice to client authors - don't just LIST "" "*" and ask for MYRIGHTS, do just RETURN SPECIAL-USE or restricted listing if you don't know how much data you're asking for.

**Comment by ksmurchison** [comment]
Barry is comfortable with the added text.
