### ISSUE TITLE
sieve-fcc: NOTIFY for non-mailto actions

### ISSUE THREAD

**Issue by brong** [ietfextra/tracking#19]
For NOTIFY actions, need to clarify either only for "mailto" type, or advice on how server should handle notify for other types.  There's no need for notify types to have a MIME representation.

Suggestions include:

* reject if it's an action that doesn't have a way to do it
* serialise the notify state in some basic way and MIMEify it, even if that's not exactly what went (e.g. XMPP notify)

**Comment by ksmurchison** [comment]
Was there consensus in the room on whether to serialize or just limit :fcc to "mailto""?

We could serialize non-mailto notifications with a simple XML or JSON body to capture the notify arguments.  Beyond that, only From and Date headers are required to store the fcc message into a mailbox

**Comment by brong** [comment]
No consensus.  I'm happy with the idea that we say "the server SHOULD generate a message with From, Date, and In-Reply-To headers and the notify arguments as the body."

**Comment by aamelnikov** [comment]
"No consensus" is a bit misleading, because I don't think the question was asked in the room. I personally was ambivalent.

**Comment by ksmurchison** [comment]
Resolved by https://github.com/ietfextra/tracking/commit/be8f3c7f65e7f2908cf3d6644872731e4aacfec6
