### ISSUE TITLE
savedate: SAVEDATESUPPORTED search key

### ISSUE THREAD

**Issue by brong** [ietfextra/tracking#21]
From IETF101.  Having a SAVEDATESUPPORTED search term would allow boolean logic to be developed to represent how you want the search to work in mailboxes where SAVEDATE isn't supported.

**Comment by brong** [comment]
Chair hat off: I would like to see the SAVEDATE search terms always return FALSE if SAVEDATESUPPORTED is FALSE.  That's a neat basis to work with.

**Comment by stephanbosch** [comment]
Addressed in latest draft.
