### ISSUE TITLE
specialuse-important: make registry have a column for "protocols supported"

### ISSUE THREAD

**Issue by brong** [ietfextra/tracking#23]
use case: \Inbox is needed for JMAP where there's not a standard name.

**Comment by barryleiba** [comment]
It's in "Usage Notes", and is already in the WG-00 version.

**Comment by brong** [comment]
Yep, thanks.  I created this before the WG-00 version was written from the IETF101 minutes, so I just tagged you on it when you joined the group :)  I'll wait for the call for adoption to expire before going further.
