### ISSUE TITLE
status-size: remove reference to 64BIT capability

### ISSUE THREAD

**Issue by brong** [ietfextra/tracking#26]
It's clear this draft will be finished first, so this isn't a problem for this draft, let 64bit fix it if needed.

**Comment by stephanbosch** [comment]
Already handled in the git version: https://github.com/ietfextra/draft-ietf-extra-imap-status-size/commit/0f38708b76b4acb45a77175dc336a15404b08a53

This ticket duplicates https://github.com/ietfextra/tracking/issues/10.
