### ISSUE TITLE
specialuse-important: make the registry say "four fields"

### ISSUE THREAD

**Issue by brong** [ietfextra/tracking#29]
In -00 the text says:

6.2.  Creation of the IMAP Mailbox Name Attributes Registry
[...]
   The registry entries will contain three fields:

   1.  Attribute Name
   2.  Description
   3.  Reference
   4.  Usage Notes

Clearly that text should say four fields.

**Comment by barryleiba** [comment]
No, clearly that text should not have a number.  In -01 it now says "the following fields", and the other two instances of "the three fields" now say "the fields".
