### ISSUE TITLE
specialuse-important: include an example of CREATE failing

### ISSUE THREAD

**Issue by brong** [ietfextra/tracking#30]
Recommendation by Chris Newman:

I recommend including this example:

      C: t6 CREATE Important (USE (\Important))
      S: t6 NO [USEATTR] \Important not supported

to remind client implementers how RFC 6154 works with unrecognized use attributes.

**Comment by barryleiba** [comment]
Resolved in -01.  I actually added three examples, to show successful creation, failure due to attribute conflict, and failure due to attribute unsupported.
