### ISSUE TITLE
status-size: clarify responses to Opsdir last call review

### ISSUE THREAD

**Issue by brong** [ietfextra/tracking#31]
There was a "not ready" review from last call.  These following areas were raised:

Reviewer: Linda Dunbar
Review result: need more complete description

After reading through the document, I find the description is not very clear.
For example:
Section 1 Introduction:
Is the “mailbox” referring to the IMAP client’s mailbox or the server mailbox
where all emails are stored?

Why do Webmail clients need to know the server side mailbox size?

Does the “mailbox size” change overtime?

**Comment by stephanbosch** [comment]
Clarified the second point:
https://github.com/ietfextra/draft-ietf-extra-imap-status-size/commit/0cbc1033a40a06ac2b2240624d3a55c61a66c030

Will not address the other ones.

**Comment by brong** [comment]
Thanks
